/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: bilgehan.korkmaz (https://sketchfab.com/bilgehan.korkmaz)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/eroded-desert-rock-b6f6b255971d4b91bb708e406671535a
title: Eroded Desert Rock
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Rock(props) {
  const { nodes, materials } = useGLTF('/rock.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={0.2} position={[props.x,props.y,props.z]}>
            <mesh geometry={nodes.rock3_low__0.geometry} material={materials['Scene_-_Root']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/rock.gltf')
